// Mori.SkyScope — Design tokens as TypeScript constants, generated from design/tokens.
// Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0.

// Generated by tools/build-design.mjs from design/ — do not edit by hand.
/** Token tree whose leaves are `var(--skyscope-…)` references, for inline styles that should follow the active CSS theme. */
export const vars = {
  "color": {
    "white": "var(--skyscope-color-white)",
    "black": "var(--skyscope-color-black)",
    "gray": {
      "50": "var(--skyscope-color-gray-50)",
      "100": "var(--skyscope-color-gray-100)",
      "200": "var(--skyscope-color-gray-200)",
      "300": "var(--skyscope-color-gray-300)",
      "400": "var(--skyscope-color-gray-400)",
      "500": "var(--skyscope-color-gray-500)",
      "600": "var(--skyscope-color-gray-600)",
      "700": "var(--skyscope-color-gray-700)",
      "800": "var(--skyscope-color-gray-800)",
      "900": "var(--skyscope-color-gray-900)",
      "950": "var(--skyscope-color-gray-950)"
    },
    "blue": {
      "50": "var(--skyscope-color-blue-50)",
      "100": "var(--skyscope-color-blue-100)",
      "200": "var(--skyscope-color-blue-200)",
      "300": "var(--skyscope-color-blue-300)",
      "400": "var(--skyscope-color-blue-400)",
      "500": "var(--skyscope-color-blue-500)",
      "600": "var(--skyscope-color-blue-600)",
      "700": "var(--skyscope-color-blue-700)",
      "800": "var(--skyscope-color-blue-800)",
      "900": "var(--skyscope-color-blue-900)"
    },
    "red": {
      "50": "var(--skyscope-color-red-50)",
      "100": "var(--skyscope-color-red-100)",
      "200": "var(--skyscope-color-red-200)",
      "300": "var(--skyscope-color-red-300)",
      "400": "var(--skyscope-color-red-400)",
      "500": "var(--skyscope-color-red-500)",
      "600": "var(--skyscope-color-red-600)",
      "700": "var(--skyscope-color-red-700)",
      "800": "var(--skyscope-color-red-800)",
      "900": "var(--skyscope-color-red-900)"
    },
    "green": {
      "50": "var(--skyscope-color-green-50)",
      "100": "var(--skyscope-color-green-100)",
      "200": "var(--skyscope-color-green-200)",
      "300": "var(--skyscope-color-green-300)",
      "400": "var(--skyscope-color-green-400)",
      "500": "var(--skyscope-color-green-500)",
      "600": "var(--skyscope-color-green-600)",
      "700": "var(--skyscope-color-green-700)",
      "800": "var(--skyscope-color-green-800)",
      "900": "var(--skyscope-color-green-900)"
    },
    "amber": {
      "50": "var(--skyscope-color-amber-50)",
      "100": "var(--skyscope-color-amber-100)",
      "200": "var(--skyscope-color-amber-200)",
      "300": "var(--skyscope-color-amber-300)",
      "400": "var(--skyscope-color-amber-400)",
      "500": "var(--skyscope-color-amber-500)",
      "600": "var(--skyscope-color-amber-600)",
      "700": "var(--skyscope-color-amber-700)",
      "800": "var(--skyscope-color-amber-800)",
      "900": "var(--skyscope-color-amber-900)"
    },
    "bg": {
      "canvas": "var(--skyscope-color-bg-canvas)",
      "surface": "var(--skyscope-color-bg-surface)",
      "subtle": "var(--skyscope-color-bg-subtle)",
      "muted": "var(--skyscope-color-bg-muted)",
      "overlay": "var(--skyscope-color-bg-overlay)"
    },
    "text": {
      "primary": "var(--skyscope-color-text-primary)",
      "secondary": "var(--skyscope-color-text-secondary)",
      "muted": "var(--skyscope-color-text-muted)",
      "inverse": "var(--skyscope-color-text-inverse)",
      "link": "var(--skyscope-color-text-link)"
    },
    "border": {
      "default": "var(--skyscope-color-border-default)",
      "strong": "var(--skyscope-color-border-strong)",
      "focus": "var(--skyscope-color-border-focus)"
    },
    "primary": {
      "default": "var(--skyscope-color-primary-default)",
      "hover": "var(--skyscope-color-primary-hover)",
      "active": "var(--skyscope-color-primary-active)",
      "subtle": "var(--skyscope-color-primary-subtle)",
      "subtleHover": "var(--skyscope-color-primary-subtle-hover)",
      "text": "var(--skyscope-color-primary-text)",
      "ring": "var(--skyscope-color-primary-ring)"
    },
    "danger": {
      "default": "var(--skyscope-color-danger-default)",
      "hover": "var(--skyscope-color-danger-hover)",
      "active": "var(--skyscope-color-danger-active)",
      "subtle": "var(--skyscope-color-danger-subtle)",
      "subtleHover": "var(--skyscope-color-danger-subtle-hover)",
      "text": "var(--skyscope-color-danger-text)",
      "ring": "var(--skyscope-color-danger-ring)"
    },
    "success": {
      "default": "var(--skyscope-color-success-default)",
      "hover": "var(--skyscope-color-success-hover)",
      "active": "var(--skyscope-color-success-active)",
      "subtle": "var(--skyscope-color-success-subtle)",
      "text": "var(--skyscope-color-success-text)"
    },
    "warning": {
      "default": "var(--skyscope-color-warning-default)",
      "hover": "var(--skyscope-color-warning-hover)",
      "active": "var(--skyscope-color-warning-active)",
      "subtle": "var(--skyscope-color-warning-subtle)",
      "text": "var(--skyscope-color-warning-text)"
    },
    "control": {
      "bg": "var(--skyscope-color-control-bg)",
      "bgHover": "var(--skyscope-color-control-bg-hover)",
      "bgDisabled": "var(--skyscope-color-control-bg-disabled)",
      "border": "var(--skyscope-color-control-border)",
      "borderHover": "var(--skyscope-color-control-border-hover)",
      "placeholder": "var(--skyscope-color-control-placeholder)",
      "textDisabled": "var(--skyscope-color-control-text-disabled)"
    }
  },
  "space": {
    "0": "var(--skyscope-space-0)",
    "1": "var(--skyscope-space-1)",
    "2": "var(--skyscope-space-2)",
    "3": "var(--skyscope-space-3)",
    "4": "var(--skyscope-space-4)",
    "5": "var(--skyscope-space-5)",
    "6": "var(--skyscope-space-6)",
    "8": "var(--skyscope-space-8)",
    "10": "var(--skyscope-space-10)",
    "12": "var(--skyscope-space-12)",
    "16": "var(--skyscope-space-16)"
  },
  "radius": {
    "none": "var(--skyscope-radius-none)",
    "sm": "var(--skyscope-radius-sm)",
    "md": "var(--skyscope-radius-md)",
    "lg": "var(--skyscope-radius-lg)",
    "xl": "var(--skyscope-radius-xl)",
    "full": "var(--skyscope-radius-full)"
  },
  "font": {
    "family": {
      "sans": "var(--skyscope-font-family-sans)",
      "mono": "var(--skyscope-font-family-mono)"
    },
    "size": {
      "xs": "var(--skyscope-font-size-xs)",
      "sm": "var(--skyscope-font-size-sm)",
      "md": "var(--skyscope-font-size-md)",
      "lg": "var(--skyscope-font-size-lg)",
      "xl": "var(--skyscope-font-size-xl)",
      "2xl": "var(--skyscope-font-size-2xl)",
      "3xl": "var(--skyscope-font-size-3xl)"
    },
    "weight": {
      "regular": "var(--skyscope-font-weight-regular)",
      "medium": "var(--skyscope-font-weight-medium)",
      "semibold": "var(--skyscope-font-weight-semibold)",
      "bold": "var(--skyscope-font-weight-bold)"
    },
    "leading": {
      "tight": "var(--skyscope-font-leading-tight)",
      "normal": "var(--skyscope-font-leading-normal)"
    }
  },
  "control": {
    "height": {
      "sm": "var(--skyscope-control-height-sm)",
      "md": "var(--skyscope-control-height-md)",
      "lg": "var(--skyscope-control-height-lg)"
    },
    "paddingX": {
      "sm": "var(--skyscope-control-padding-x-sm)",
      "md": "var(--skyscope-control-padding-x-md)",
      "lg": "var(--skyscope-control-padding-x-lg)"
    },
    "fontSize": {
      "sm": "var(--skyscope-control-font-size-sm)",
      "md": "var(--skyscope-control-font-size-md)",
      "lg": "var(--skyscope-control-font-size-lg)"
    },
    "radius": "var(--skyscope-control-radius)",
    "borderWidth": "var(--skyscope-control-border-width)"
  },
  "motion": {
    "duration": {
      "fast": "var(--skyscope-motion-duration-fast)",
      "normal": "var(--skyscope-motion-duration-normal)",
      "slow": "var(--skyscope-motion-duration-slow)"
    },
    "easing": {
      "standard": "var(--skyscope-motion-easing-standard)",
      "emphasized": "var(--skyscope-motion-easing-emphasized)"
    }
  },
  "z": {
    "dropdown": "var(--skyscope-z-dropdown)",
    "sticky": "var(--skyscope-z-sticky)",
    "overlay": "var(--skyscope-z-overlay)",
    "modal": "var(--skyscope-z-modal)",
    "popover": "var(--skyscope-z-popover)",
    "toast": "var(--skyscope-z-toast)"
  },
  "shadow": {
    "sm": "var(--skyscope-shadow-sm)",
    "md": "var(--skyscope-shadow-md)",
    "lg": "var(--skyscope-shadow-lg)"
  },
  "focus": {
    "ring": "var(--skyscope-focus-ring)",
    "ringDanger": "var(--skyscope-focus-ring-danger)"
  }
} as const;
/** Token tree whose leaves are the bare CSS custom property names (`--skyscope-…`), for setProperty/getPropertyValue. */
export const cssVarNames = {
  "color": {
    "white": "--skyscope-color-white",
    "black": "--skyscope-color-black",
    "gray": {
      "50": "--skyscope-color-gray-50",
      "100": "--skyscope-color-gray-100",
      "200": "--skyscope-color-gray-200",
      "300": "--skyscope-color-gray-300",
      "400": "--skyscope-color-gray-400",
      "500": "--skyscope-color-gray-500",
      "600": "--skyscope-color-gray-600",
      "700": "--skyscope-color-gray-700",
      "800": "--skyscope-color-gray-800",
      "900": "--skyscope-color-gray-900",
      "950": "--skyscope-color-gray-950"
    },
    "blue": {
      "50": "--skyscope-color-blue-50",
      "100": "--skyscope-color-blue-100",
      "200": "--skyscope-color-blue-200",
      "300": "--skyscope-color-blue-300",
      "400": "--skyscope-color-blue-400",
      "500": "--skyscope-color-blue-500",
      "600": "--skyscope-color-blue-600",
      "700": "--skyscope-color-blue-700",
      "800": "--skyscope-color-blue-800",
      "900": "--skyscope-color-blue-900"
    },
    "red": {
      "50": "--skyscope-color-red-50",
      "100": "--skyscope-color-red-100",
      "200": "--skyscope-color-red-200",
      "300": "--skyscope-color-red-300",
      "400": "--skyscope-color-red-400",
      "500": "--skyscope-color-red-500",
      "600": "--skyscope-color-red-600",
      "700": "--skyscope-color-red-700",
      "800": "--skyscope-color-red-800",
      "900": "--skyscope-color-red-900"
    },
    "green": {
      "50": "--skyscope-color-green-50",
      "100": "--skyscope-color-green-100",
      "200": "--skyscope-color-green-200",
      "300": "--skyscope-color-green-300",
      "400": "--skyscope-color-green-400",
      "500": "--skyscope-color-green-500",
      "600": "--skyscope-color-green-600",
      "700": "--skyscope-color-green-700",
      "800": "--skyscope-color-green-800",
      "900": "--skyscope-color-green-900"
    },
    "amber": {
      "50": "--skyscope-color-amber-50",
      "100": "--skyscope-color-amber-100",
      "200": "--skyscope-color-amber-200",
      "300": "--skyscope-color-amber-300",
      "400": "--skyscope-color-amber-400",
      "500": "--skyscope-color-amber-500",
      "600": "--skyscope-color-amber-600",
      "700": "--skyscope-color-amber-700",
      "800": "--skyscope-color-amber-800",
      "900": "--skyscope-color-amber-900"
    },
    "bg": {
      "canvas": "--skyscope-color-bg-canvas",
      "surface": "--skyscope-color-bg-surface",
      "subtle": "--skyscope-color-bg-subtle",
      "muted": "--skyscope-color-bg-muted",
      "overlay": "--skyscope-color-bg-overlay"
    },
    "text": {
      "primary": "--skyscope-color-text-primary",
      "secondary": "--skyscope-color-text-secondary",
      "muted": "--skyscope-color-text-muted",
      "inverse": "--skyscope-color-text-inverse",
      "link": "--skyscope-color-text-link"
    },
    "border": {
      "default": "--skyscope-color-border-default",
      "strong": "--skyscope-color-border-strong",
      "focus": "--skyscope-color-border-focus"
    },
    "primary": {
      "default": "--skyscope-color-primary-default",
      "hover": "--skyscope-color-primary-hover",
      "active": "--skyscope-color-primary-active",
      "subtle": "--skyscope-color-primary-subtle",
      "subtleHover": "--skyscope-color-primary-subtle-hover",
      "text": "--skyscope-color-primary-text",
      "ring": "--skyscope-color-primary-ring"
    },
    "danger": {
      "default": "--skyscope-color-danger-default",
      "hover": "--skyscope-color-danger-hover",
      "active": "--skyscope-color-danger-active",
      "subtle": "--skyscope-color-danger-subtle",
      "subtleHover": "--skyscope-color-danger-subtle-hover",
      "text": "--skyscope-color-danger-text",
      "ring": "--skyscope-color-danger-ring"
    },
    "success": {
      "default": "--skyscope-color-success-default",
      "hover": "--skyscope-color-success-hover",
      "active": "--skyscope-color-success-active",
      "subtle": "--skyscope-color-success-subtle",
      "text": "--skyscope-color-success-text"
    },
    "warning": {
      "default": "--skyscope-color-warning-default",
      "hover": "--skyscope-color-warning-hover",
      "active": "--skyscope-color-warning-active",
      "subtle": "--skyscope-color-warning-subtle",
      "text": "--skyscope-color-warning-text"
    },
    "control": {
      "bg": "--skyscope-color-control-bg",
      "bgHover": "--skyscope-color-control-bg-hover",
      "bgDisabled": "--skyscope-color-control-bg-disabled",
      "border": "--skyscope-color-control-border",
      "borderHover": "--skyscope-color-control-border-hover",
      "placeholder": "--skyscope-color-control-placeholder",
      "textDisabled": "--skyscope-color-control-text-disabled"
    }
  },
  "space": {
    "0": "--skyscope-space-0",
    "1": "--skyscope-space-1",
    "2": "--skyscope-space-2",
    "3": "--skyscope-space-3",
    "4": "--skyscope-space-4",
    "5": "--skyscope-space-5",
    "6": "--skyscope-space-6",
    "8": "--skyscope-space-8",
    "10": "--skyscope-space-10",
    "12": "--skyscope-space-12",
    "16": "--skyscope-space-16"
  },
  "radius": {
    "none": "--skyscope-radius-none",
    "sm": "--skyscope-radius-sm",
    "md": "--skyscope-radius-md",
    "lg": "--skyscope-radius-lg",
    "xl": "--skyscope-radius-xl",
    "full": "--skyscope-radius-full"
  },
  "font": {
    "family": {
      "sans": "--skyscope-font-family-sans",
      "mono": "--skyscope-font-family-mono"
    },
    "size": {
      "xs": "--skyscope-font-size-xs",
      "sm": "--skyscope-font-size-sm",
      "md": "--skyscope-font-size-md",
      "lg": "--skyscope-font-size-lg",
      "xl": "--skyscope-font-size-xl",
      "2xl": "--skyscope-font-size-2xl",
      "3xl": "--skyscope-font-size-3xl"
    },
    "weight": {
      "regular": "--skyscope-font-weight-regular",
      "medium": "--skyscope-font-weight-medium",
      "semibold": "--skyscope-font-weight-semibold",
      "bold": "--skyscope-font-weight-bold"
    },
    "leading": {
      "tight": "--skyscope-font-leading-tight",
      "normal": "--skyscope-font-leading-normal"
    }
  },
  "control": {
    "height": {
      "sm": "--skyscope-control-height-sm",
      "md": "--skyscope-control-height-md",
      "lg": "--skyscope-control-height-lg"
    },
    "paddingX": {
      "sm": "--skyscope-control-padding-x-sm",
      "md": "--skyscope-control-padding-x-md",
      "lg": "--skyscope-control-padding-x-lg"
    },
    "fontSize": {
      "sm": "--skyscope-control-font-size-sm",
      "md": "--skyscope-control-font-size-md",
      "lg": "--skyscope-control-font-size-lg"
    },
    "radius": "--skyscope-control-radius",
    "borderWidth": "--skyscope-control-border-width"
  },
  "motion": {
    "duration": {
      "fast": "--skyscope-motion-duration-fast",
      "normal": "--skyscope-motion-duration-normal",
      "slow": "--skyscope-motion-duration-slow"
    },
    "easing": {
      "standard": "--skyscope-motion-easing-standard",
      "emphasized": "--skyscope-motion-easing-emphasized"
    }
  },
  "z": {
    "dropdown": "--skyscope-z-dropdown",
    "sticky": "--skyscope-z-sticky",
    "overlay": "--skyscope-z-overlay",
    "modal": "--skyscope-z-modal",
    "popover": "--skyscope-z-popover",
    "toast": "--skyscope-z-toast"
  },
  "shadow": {
    "sm": "--skyscope-shadow-sm",
    "md": "--skyscope-shadow-md",
    "lg": "--skyscope-shadow-lg"
  },
  "focus": {
    "ring": "--skyscope-focus-ring",
    "ringDanger": "--skyscope-focus-ring-danger"
  }
} as const;
/** Fully resolved token values per theme name, for renderers that cannot read CSS variables (canvas, WebGL). */
export const themes = {
  "dark": {
    "color": {
      "white": "#ffffff",
      "black": "#000000",
      "gray": {
        "50": "#f8fafc",
        "100": "#f1f5f9",
        "200": "#e2e8f0",
        "300": "#cbd5e1",
        "400": "#94a3b8",
        "500": "#64748b",
        "600": "#475569",
        "700": "#334155",
        "800": "#1e293b",
        "900": "#0f172a",
        "950": "#020617"
      },
      "blue": {
        "50": "#eff6ff",
        "100": "#dbeafe",
        "200": "#bfdbfe",
        "300": "#93c5fd",
        "400": "#60a5fa",
        "500": "#3b82f6",
        "600": "#2563eb",
        "700": "#1d4ed8",
        "800": "#1e40af",
        "900": "#1e3a8a"
      },
      "red": {
        "50": "#fef2f2",
        "100": "#fee2e2",
        "200": "#fecaca",
        "300": "#fca5a5",
        "400": "#f87171",
        "500": "#ef4444",
        "600": "#dc2626",
        "700": "#b91c1c",
        "800": "#991b1b",
        "900": "#7f1d1d"
      },
      "green": {
        "50": "#f0fdf4",
        "100": "#dcfce7",
        "200": "#bbf7d0",
        "300": "#86efac",
        "400": "#4ade80",
        "500": "#22c55e",
        "600": "#16a34a",
        "700": "#15803d",
        "800": "#166534",
        "900": "#14532d"
      },
      "amber": {
        "50": "#fffbeb",
        "100": "#fef3c7",
        "200": "#fde68a",
        "300": "#fcd34d",
        "400": "#fbbf24",
        "500": "#f59e0b",
        "600": "#d97706",
        "700": "#b45309",
        "800": "#92400e",
        "900": "#78350f"
      },
      "bg": {
        "canvas": "#020617",
        "surface": "#0f172a",
        "subtle": "#1e293b",
        "muted": "#334155",
        "overlay": "rgba(2, 6, 23, 0.65)"
      },
      "text": {
        "primary": "#f8fafc",
        "secondary": "#94a3b8",
        "muted": "#64748b",
        "inverse": "#0f172a",
        "link": "#60a5fa"
      },
      "border": {
        "default": "#1e293b",
        "strong": "#334155",
        "focus": "#60a5fa"
      },
      "primary": {
        "default": "#3b82f6",
        "hover": "#60a5fa",
        "active": "#93c5fd",
        "subtle": "rgba(59, 130, 246, 0.15)",
        "subtleHover": "rgba(59, 130, 246, 0.25)",
        "text": "#ffffff",
        "ring": "rgba(59, 130, 246, 0.45)"
      },
      "danger": {
        "default": "#ef4444",
        "hover": "#f87171",
        "active": "#fca5a5",
        "subtle": "rgba(239, 68, 68, 0.15)",
        "subtleHover": "rgba(239, 68, 68, 0.25)",
        "text": "#ffffff",
        "ring": "rgba(239, 68, 68, 0.45)"
      },
      "success": {
        "default": "#22c55e",
        "hover": "#4ade80",
        "active": "#86efac",
        "subtle": "rgba(34, 197, 94, 0.15)",
        "text": "#020617"
      },
      "warning": {
        "default": "#fbbf24",
        "hover": "#fcd34d",
        "active": "#fde68a",
        "subtle": "rgba(245, 158, 11, 0.15)",
        "text": "#020617"
      },
      "control": {
        "bg": "#0f172a",
        "bgHover": "#1e293b",
        "bgDisabled": "#1e293b",
        "border": "#334155",
        "borderHover": "#475569",
        "placeholder": "#64748b",
        "textDisabled": "#475569"
      }
    },
    "space": {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "8": "32px",
      "10": "40px",
      "12": "48px",
      "16": "64px"
    },
    "radius": {
      "none": "0px",
      "sm": "4px",
      "md": "6px",
      "lg": "10px",
      "xl": "16px",
      "full": "9999px"
    },
    "font": {
      "family": {
        "sans": "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
        "mono": "ui-monospace, 'Cascadia Code', 'Segoe UI Mono', Consolas, monospace"
      },
      "size": {
        "xs": "12px",
        "sm": "13px",
        "md": "14px",
        "lg": "16px",
        "xl": "18px",
        "2xl": "22px",
        "3xl": "28px"
      },
      "weight": {
        "regular": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700"
      },
      "leading": {
        "tight": "1.25",
        "normal": "1.5"
      }
    },
    "control": {
      "height": {
        "sm": "28px",
        "md": "34px",
        "lg": "40px"
      },
      "paddingX": {
        "sm": "8px",
        "md": "12px",
        "lg": "16px"
      },
      "fontSize": {
        "sm": "13px",
        "md": "14px",
        "lg": "16px"
      },
      "radius": "6px",
      "borderWidth": "1px"
    },
    "motion": {
      "duration": {
        "fast": "100ms",
        "normal": "180ms",
        "slow": "300ms"
      },
      "easing": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized": "cubic-bezier(0.3, 0, 0, 1)"
      }
    },
    "z": {
      "dropdown": "1000",
      "sticky": "1100",
      "overlay": "1200",
      "modal": "1300",
      "popover": "1400",
      "toast": "1500"
    },
    "shadow": {
      "sm": "0 1px 2px rgba(0, 0, 0, 0.4)",
      "md": "0 4px 12px rgba(0, 0, 0, 0.5), 0 1px 3px rgba(0, 0, 0, 0.4)",
      "lg": "0 12px 32px rgba(0, 0, 0, 0.6), 0 2px 6px rgba(0, 0, 0, 0.4)"
    },
    "focus": {
      "ring": "0 0 0 3px rgba(59, 130, 246, 0.45)",
      "ringDanger": "0 0 0 3px rgba(239, 68, 68, 0.45)"
    }
  },
  "light": {
    "color": {
      "white": "#ffffff",
      "black": "#000000",
      "gray": {
        "50": "#f8fafc",
        "100": "#f1f5f9",
        "200": "#e2e8f0",
        "300": "#cbd5e1",
        "400": "#94a3b8",
        "500": "#64748b",
        "600": "#475569",
        "700": "#334155",
        "800": "#1e293b",
        "900": "#0f172a",
        "950": "#020617"
      },
      "blue": {
        "50": "#eff6ff",
        "100": "#dbeafe",
        "200": "#bfdbfe",
        "300": "#93c5fd",
        "400": "#60a5fa",
        "500": "#3b82f6",
        "600": "#2563eb",
        "700": "#1d4ed8",
        "800": "#1e40af",
        "900": "#1e3a8a"
      },
      "red": {
        "50": "#fef2f2",
        "100": "#fee2e2",
        "200": "#fecaca",
        "300": "#fca5a5",
        "400": "#f87171",
        "500": "#ef4444",
        "600": "#dc2626",
        "700": "#b91c1c",
        "800": "#991b1b",
        "900": "#7f1d1d"
      },
      "green": {
        "50": "#f0fdf4",
        "100": "#dcfce7",
        "200": "#bbf7d0",
        "300": "#86efac",
        "400": "#4ade80",
        "500": "#22c55e",
        "600": "#16a34a",
        "700": "#15803d",
        "800": "#166534",
        "900": "#14532d"
      },
      "amber": {
        "50": "#fffbeb",
        "100": "#fef3c7",
        "200": "#fde68a",
        "300": "#fcd34d",
        "400": "#fbbf24",
        "500": "#f59e0b",
        "600": "#d97706",
        "700": "#b45309",
        "800": "#92400e",
        "900": "#78350f"
      },
      "bg": {
        "canvas": "#f8fafc",
        "surface": "#ffffff",
        "subtle": "#f1f5f9",
        "muted": "#e2e8f0",
        "overlay": "rgba(15, 23, 42, 0.45)"
      },
      "text": {
        "primary": "#0f172a",
        "secondary": "#475569",
        "muted": "#94a3b8",
        "inverse": "#ffffff",
        "link": "#2563eb"
      },
      "border": {
        "default": "#e2e8f0",
        "strong": "#cbd5e1",
        "focus": "#3b82f6"
      },
      "primary": {
        "default": "#2563eb",
        "hover": "#1d4ed8",
        "active": "#1e40af",
        "subtle": "#eff6ff",
        "subtleHover": "#dbeafe",
        "text": "#ffffff",
        "ring": "#bfdbfe"
      },
      "danger": {
        "default": "#dc2626",
        "hover": "#b91c1c",
        "active": "#991b1b",
        "subtle": "#fef2f2",
        "subtleHover": "#fee2e2",
        "text": "#ffffff",
        "ring": "#fecaca"
      },
      "success": {
        "default": "#16a34a",
        "hover": "#15803d",
        "active": "#166534",
        "subtle": "#f0fdf4",
        "text": "#ffffff"
      },
      "warning": {
        "default": "#f59e0b",
        "hover": "#d97706",
        "active": "#b45309",
        "subtle": "#fffbeb",
        "text": "#0f172a"
      },
      "control": {
        "bg": "#ffffff",
        "bgHover": "#f8fafc",
        "bgDisabled": "#f1f5f9",
        "border": "#cbd5e1",
        "borderHover": "#94a3b8",
        "placeholder": "#94a3b8",
        "textDisabled": "#94a3b8"
      }
    },
    "space": {
      "0": "0px",
      "1": "4px",
      "2": "8px",
      "3": "12px",
      "4": "16px",
      "5": "20px",
      "6": "24px",
      "8": "32px",
      "10": "40px",
      "12": "48px",
      "16": "64px"
    },
    "radius": {
      "none": "0px",
      "sm": "4px",
      "md": "6px",
      "lg": "10px",
      "xl": "16px",
      "full": "9999px"
    },
    "font": {
      "family": {
        "sans": "system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
        "mono": "ui-monospace, 'Cascadia Code', 'Segoe UI Mono', Consolas, monospace"
      },
      "size": {
        "xs": "12px",
        "sm": "13px",
        "md": "14px",
        "lg": "16px",
        "xl": "18px",
        "2xl": "22px",
        "3xl": "28px"
      },
      "weight": {
        "regular": "400",
        "medium": "500",
        "semibold": "600",
        "bold": "700"
      },
      "leading": {
        "tight": "1.25",
        "normal": "1.5"
      }
    },
    "control": {
      "height": {
        "sm": "28px",
        "md": "34px",
        "lg": "40px"
      },
      "paddingX": {
        "sm": "8px",
        "md": "12px",
        "lg": "16px"
      },
      "fontSize": {
        "sm": "13px",
        "md": "14px",
        "lg": "16px"
      },
      "radius": "6px",
      "borderWidth": "1px"
    },
    "motion": {
      "duration": {
        "fast": "100ms",
        "normal": "180ms",
        "slow": "300ms"
      },
      "easing": {
        "standard": "cubic-bezier(0.2, 0, 0, 1)",
        "emphasized": "cubic-bezier(0.3, 0, 0, 1)"
      }
    },
    "z": {
      "dropdown": "1000",
      "sticky": "1100",
      "overlay": "1200",
      "modal": "1300",
      "popover": "1400",
      "toast": "1500"
    },
    "shadow": {
      "sm": "0 1px 2px rgba(15, 23, 42, 0.06)",
      "md": "0 4px 12px rgba(15, 23, 42, 0.10), 0 1px 3px rgba(15, 23, 42, 0.06)",
      "lg": "0 12px 32px rgba(15, 23, 42, 0.16), 0 2px 6px rgba(15, 23, 42, 0.08)"
    },
    "focus": {
      "ring": "0 0 0 3px #bfdbfe",
      "ringDanger": "0 0 0 3px #fecaca"
    }
  }
} as const;
/** Name of a built-in theme; "light" is the :root theme, the others are `[data-theme=name]` overrides. */
export type ThemeName = keyof typeof themes;
/** Every built-in theme name, in the order the theme files were read. */
export const themeNames = Object.keys(themes) as ThemeName[];
