// Mori.SkyScope — Synthetic source: deterministic waveforms pushed as frames from a timer, for demos and benches.
// Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0.

using Mori.SkyScope.Core.Streaming;

namespace Mori.SkyScope.Core.Sources;

/// <summary>One generated channel.</summary>
/// <param name="Id">Channel id.</param>
/// <param name="Spec">The waveform.</param>
/// <param name="Name">Display name; <c>ch&lt;Id&gt;</c> when null.</param>
/// <param name="Unit">Unit label.</param>
/// <param name="Kind">Channel kind; analog when null.</param>
public sealed record SyntheticChannel(int Id, SynthSpec Spec, string? Name = null, string? Unit = null, ChannelKind? Kind = null);

/// <summary>Configuration object for <see cref="SyntheticSource.StartAsync"/>; the defaults give 8 channels at 1 kHz in 20 ms frames.</summary>
public sealed record SyntheticSourceConfig
{
    /// <summary>Explicit channels; when null, <see cref="ChannelCount"/> mixed waveforms are generated.</summary>
    public IReadOnlyList<SyntheticChannel>? Channels { get; init; }
    /// <summary>Channels generated by <see cref="AutoChannels"/> when <see cref="Channels"/> is null.</summary>
    public int ChannelCount { get; init; } = 8;
    /// <summary>Samples per second per channel.</summary>
    public double Rate { get; init; } = 1000;
    /// <summary>Frame period.</summary>
    public double BatchMs { get; init; } = 20;
    /// <summary>Base noise seed; channel <c>i</c> uses <c>Seed + i</c>.</summary>
    public int Seed { get; init; }
    /// <summary>Send as quantized i16 (enc 2) instead of f32 — halves bandwidth, exercises the dequantizer.</summary>
    public bool Quantized { get; init; }

    /// <summary><paramref name="count"/> channels with ids 1…count cycling through sine, triangle, sawtooth, square and noise, with varied frequency, amplitude, offset, phase and noise.</summary>
    public static IReadOnlyList<SyntheticChannel> AutoChannels(int count, int seed = 0)
    {
        Waveform[] waves = [Waveform.Sine, Waveform.Triangle, Waveform.Sawtooth, Waveform.Square, Waveform.Noise];
        return Enumerable.Range(0, count).Select(i => new SyntheticChannel(i + 1, new SynthSpec(waves[i % waves.Length])
        {
            Frequency = 0.1 + i % 10 * 0.37, Amplitude = 1 + i % 4, Offset = i % 3 - 1, Phase = i * 0.5, Noise = 0.05 + i % 5 * 0.02, Seed = seed + i,
        }, $"ch{i + 1}")).ToList();
    }
}

/// <summary>Generates frames on a timer — the demo/bench source. Deterministic for a given seed and start time.</summary>
public sealed class SyntheticSource : ISource
{
    /// <summary><c>"synthetic"</c>.</summary>
    public string Type => "synthetic";
    private CancellationTokenSource? _cts;
    private Task? _loop;

    /// <summary>Declare the channels as regular at the configured rate and start a background loop that pushes one frame every <see cref="SyntheticSourceConfig.BatchMs"/> starting at the clock's current time. Frames are pushed from the loop's thread.</summary>
    public Task StartAsync(SourceContext ctx, object? config, CancellationToken ct = default)
    {
        var cfg = config as SyntheticSourceConfig ?? new SyntheticSourceConfig();
        var channels = cfg.Channels ?? SyntheticSourceConfig.AutoChannels(cfg.ChannelCount, cfg.Seed);
        var dt = 1 / cfg.Rate;
        var count = Math.Max(1, (int)Math.Round(cfg.Rate * cfg.BatchMs / 1000));
        foreach (var c in channels)
            ctx.Signals.DeclareChannel(new ChannelInfo(c.Id, c.Name ?? $"ch{c.Id}") { Unit = c.Unit, Kind = c.Kind, Rate = cfg.Rate, Timing = ChannelTiming.Regular });

        _cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
        var token = _cts.Token;
        _loop = Task.Run(async () =>
        {
            using var timer = new PeriodicTimer(TimeSpan.FromMilliseconds(cfg.BatchMs));
            var nextT = ctx.Clock.Now();
            uint seq = 0; var index = 0;
            while (await timer.WaitForNextTickAsync(token).ConfigureAwait(false))
            {
                var tStart = nextT;
                var frameChannels = new List<FrameChannel>(channels.Count);
                foreach (var c in channels)
                {
                    var values = Synth.Synthesize(c.Spec, tStart, dt, count, index);
                    if (!cfg.Quantized) { frameChannels.Add(FrameChannel.Regular((ushort)c.Id, tStart, dt, values)); continue; }
                    var offset = (float)c.Spec.Offset;
                    var scale = (float)((c.Spec.Amplitude + c.Spec.Noise) / 32767);
                    var q = values.Select(v => (short)Math.Clamp(Math.Round((v - offset) / scale), -32768, 32767)).ToArray();
                    frameChannels.Add(FrameChannel.Quantized((ushort)c.Id, tStart, dt, scale, offset, q));
                }
                nextT = tStart + count * dt;
                index += count;
                ctx.Signals.PushFrame(new SkyScopeFrame(seq++, tStart, frameChannels));
            }
        }, token);
        return Task.CompletedTask;
    }

    /// <summary>Cancel the loop and wait for it to exit; safe to call when not started.</summary>
    public async Task StopAsync()
    {
        if (_cts is null) return;
        await _cts.CancelAsync();
        try { if (_loop is not null) await _loop; } catch (OperationCanceledException) { }
        _cts.Dispose(); _cts = null; _loop = null;
    }
}

/// <summary>Factory for <see cref="SyntheticSource"/>.</summary>
[SkyScopeSource]
public sealed class SyntheticSourceFactory : ISourceFactory
{
    /// <summary><c>"synthetic"</c>.</summary>
    public string Type => "synthetic";
    /// <summary>Name for pickers.</summary>
    public string DisplayName => "Synthetic signals";
    /// <summary>Signals only.</summary>
    public SourceCapabilities Capabilities => SourceCapabilities.Signals;
    /// <summary>JSON Schema with <c>channelCount</c>, <c>rate</c>, <c>batchMs</c>, <c>seed</c> and <c>quantized</c>, mirroring <see cref="SyntheticSourceConfig"/>.</summary>
    public string? ConfigSchema => """{"type":"object","properties":{"channelCount":{"type":"integer","minimum":1,"default":8},"rate":{"type":"number","minimum":1,"default":1000},"batchMs":{"type":"number","minimum":1,"default":20},"seed":{"type":"integer","default":0},"quantized":{"type":"boolean","default":false}}}""";
    /// <summary>A new, not yet started source.</summary>
    public ISource Create() => new SyntheticSource();
}
