<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Authors>Cristian Mori</Authors>
    <Copyright>Copyright 2026 Cristian Mori</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/CristianMori/Mori.SkyScope</RepositoryUrl>
    <Version>0.1.0</Version>
    <PackageProjectUrl>https://github.com/CristianMori/Mori.SkyScope</PackageProjectUrl>
    <PackageTags>charts;realtime;robotics;gauges;dashboard;skia;blazor;wpf;react</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <IsPackable>true</IsPackable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1573;CS1574;CS1570</NoWarn>
  </PropertyGroup>
  <ItemGroup Condition="'$(IsPackable)' != 'false'">
    <None Include="$(MSBuildThisFileDirectory)../docs/nuget-README.md" Pack="true" PackagePath="README.md" Visible="false" />
  </ItemGroup>
</Project>
