// Mori.SkyScope — Generates CSS custom properties, TypeScript constants and C# constants from the design tokens, and the shared stylesheet.
// Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0.

// Builds the design system from its source of truth:
//   design/tokens/**     -> CSS custom properties, TS theme objects, C# constants
//   design/styles/*.css  -> one shared component stylesheet for every web renderer
// Usage: node tools/build-design.mjs
import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
/** Reads a repo-relative file as UTF-8. */
const rd = (p) => fs.readFileSync(path.join(root, p), "utf8");
/** Writes a repo-relative file, creating its directory. */
const wr = (p, s) => { fs.mkdirSync(path.dirname(path.join(root, p)), { recursive: true }); fs.writeFileSync(path.join(root, p), s); };
/** Banner placed at the top of every generated file. */
const HEADER = "Generated by tools/build-design.mjs from design/ — do not edit by hand.";

// ---- tokens -------------------------------------------------------------
// base.json holds the palette and scales; each themes/<name>.json overrides a subset and may reference base tokens as {a.b.c}.
const base = JSON.parse(rd("design/tokens/base.json"));
const themeDir = path.join(root, "design/tokens/themes");
const themes = Object.fromEntries(
  fs.readdirSync(themeDir).filter((f) => f.endsWith(".json"))
    .map((f) => [path.basename(f, ".json"), JSON.parse(rd(`design/tokens/themes/${f}`))]));
if (!themes.light) throw new Error("design/tokens/themes/light.json is required (it is the :root theme)");

/** Flattens a nested token tree into { "a.b.c": "value" }; `$`-prefixed keys are metadata and `{ $value }` leaves are unwrapped. */
function flatten(obj, prefix = [], out = {}) {
  for (const [k, v] of Object.entries(obj)) {
    if (k.startsWith("$")) continue;
    const p = [...prefix, k];
    if (v && typeof v === "object" && !("$value" in v)) flatten(v, p, out);
    else out[p.join(".")] = String(v && typeof v === "object" ? v.$value : v);
  }
  return out;
}
/** Substitutes `{token.path}` references in every value, recursively and memoized; throws on an unknown token or a cycle. */
function resolve(flat) {
  const out = {};
  const get = (k, stack = []) => {
    if (k in out) return out[k];
    if (!(k in flat)) throw new Error(`Unknown token {${k}} referenced from ${stack.join(" -> ") || "top level"}`);
    if (stack.includes(k)) throw new Error(`Token cycle: ${[...stack, k].join(" -> ")}`);
    out[k] = flat[k].replace(/\{([^}]+)\}/g, (_, ref) => get(ref, [...stack, k]));
    return out[k];
  };
  for (const k of Object.keys(flat)) get(k);
  return out;
}
/** camelCase -> kebab-case. */
const kebab = (s) => s.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
/** Token path -> CSS custom property name, e.g. "color.textSecondary" -> "--skyscope-color-text-secondary". */
const cssVar = (k) => `--skyscope-${k.split(".").map(kebab).join("-")}`;
/** Token path -> C# identifier, e.g. "color.gray.50" -> "ColorGray50". */
const pascal = (k) => k.split(/[.\-]/).map((s) => s[0].toUpperCase() + s.slice(1)).join("");

// Resolve every theme over the base so each has the full key set; the light theme defines the canonical key list.
const baseFlat = flatten(base);
const themeFlat = Object.fromEntries(Object.entries(themes).map(([n, t]) => [n, flatten(t)]));
const resolved = Object.fromEntries(Object.entries(themeFlat).map(([n, t]) => [n, resolve({ ...baseFlat, ...t })]));
const allKeys = Object.keys(resolved.light).sort();

// CSS custom properties: light is :root, other themes are [data-theme=name] overrides
let css = `/* Mori.SkyScope design tokens as CSS custom properties. Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0. */\n/* ${HEADER} */\n:root {\n`;
for (const k of allKeys) css += `  ${cssVar(k)}: ${resolved.light[k]};\n`;
css += "}\n";
for (const [name, t] of Object.entries(themeFlat)) {
  if (name === "light") continue;
  css += `[data-theme="${name}"] {\n`;
  for (const k of Object.keys(t).sort()) css += `  ${cssVar(k)}: ${resolved[name][k]};\n`;
  css += "}\n";
}

// TS: nested `vars` (var() references) and per-theme resolved values
/** Rebuilds a nested object from flat "a.b.c" keys, with `leaf(key)` producing each leaf value. */
const nest = (flat, leaf) => {
  const o = {};
  for (const k of Object.keys(flat)) {
    const parts = k.split(".");
    let cur = o;
    for (const p of parts.slice(0, -1)) cur = cur[p] ??= {};
    cur[parts[parts.length - 1]] = leaf(k);
  }
  return o;
};
const ts = `// Mori.SkyScope — Design tokens as TypeScript constants, generated from design/tokens.
// Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0.

// ${HEADER}
/** Token tree whose leaves are \`var(--skyscope-…)\` references, for inline styles that should follow the active CSS theme. */
export const vars = ${JSON.stringify(nest(resolved.light, (k) => `var(${cssVar(k)})`), null, 2)} as const;
/** Token tree whose leaves are the bare CSS custom property names (\`--skyscope-…\`), for setProperty/getPropertyValue. */
export const cssVarNames = ${JSON.stringify(nest(resolved.light, (k) => cssVar(k)), null, 2)} as const;
/** Fully resolved token values per theme name, for renderers that cannot read CSS variables (canvas, WebGL). */
export const themes = ${JSON.stringify(Object.fromEntries(Object.entries(resolved).map(([n, t]) => [n, nest(t, (k) => t[k])])), null, 2)} as const;
/** Name of a built-in theme; "light" is the :root theme, the others are \`[data-theme=name]\` overrides. */
export type ThemeName = keyof typeof themes;
/** Every built-in theme name, in the order the theme files were read. */
export const themeNames = Object.keys(themes) as ThemeName[];
`;

// C#: resolved values for renderers that don't speak CSS (WPF/WinForms) + var names for those that do
let cs = `// Mori.SkyScope — Design tokens as C# constants, generated from design/tokens.\n// Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0.\n\n// <auto-generated> ${HEADER} </auto-generated>\nnamespace Mori.SkyScope.Core.Theming;\n\npublic static class Tokens\n{\n`;
cs += "    /// <summary>CSS custom property names, for web renderers.</summary>\n    public static class Css\n    {\n";
for (const k of allKeys) cs += `        public const string ${pascal(k)} = "${cssVar(k)}";\n`;
cs += "    }\n";
for (const [name, t] of Object.entries(resolved)) {
  cs += `\n    /// <summary>Resolved values for the "${name}" theme.</summary>\n    public static class ${pascal(name)}\n    {\n`;
  for (const k of allKeys) cs += `        public const string ${pascal(k)} = "${t[k].replace(/"/g, '\\"')}";\n`;
  cs += "    }\n";
}
cs += "\n    public static readonly string[] ThemeNames = [" + Object.keys(resolved).map((n) => `"${n}"`).join(", ") + "];\n}\n";

// ---- component styles ---------------------------------------------------
// Concatenate design/styles/*.css in name order after the variables so one file carries both the tokens and the component rules.
const stylesDir = path.join(root, "design/styles");
const styleFiles = fs.readdirSync(stylesDir).filter((f) => f.endsWith(".css")).sort();
let components = `/* Mori.SkyScope shared component stylesheet. Author: Cristian Mori. Copyright 2026 Cristian Mori. Licensed under the Apache License, Version 2.0. */\n/* ${HEADER} */\n`;
for (const f of styleFiles) components += `\n/* ---- ${f} ---- */\n${rd(`design/styles/${f}`)}`;
const bundle = css + components;

// ---- outputs ------------------------------------------------------------
// tokens package: variables only; react and Blazor: variables + component styles; Core: C# constants.
wr("ts/packages/tokens/src/tokens.css", css);
wr("ts/packages/tokens/src/index.ts", ts);
wr("ts/packages/react/src/styles.css", bundle);
wr("dotnet/Mori.SkyScope.Blazor/wwwroot/skyscope.css", bundle);
wr("dotnet/Mori.SkyScope.Core/Theming/Tokens.g.cs", cs);
console.log(`design: ${allKeys.length} tokens, ${Object.keys(themes).length} themes, ${styleFiles.length} style files -> 5 outputs`);
